#!/usr/bin/env python3

from cli import args
from renderer import render
from diagram import get_diagram

diagram = get_diagram(args.input)

print(args.output)
with open(args.output, 'w') as file:
    file.write(render(diagram))
